const ARTICLES=[1,2,3,4,5,6,7,8,9,10,11,17,18,20,22,23,24,27,28,32,33,34,41,42,43,45,50,51,55,61,62,75,92,97,98,102,103,110,111];
const OLD_KEY='un-charta-progress-v1',KEY='un-charta-study-v2',DEADLINE=new Date('2026-10-12T00:00:00+03:00'),DAY=86400000,REVIEW_DAYS=4;
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const oldLearned=JSON.parse(localStorage.getItem(OLD_KEY)||'[]');
let state=Object.assign({learned:oldLearned,review:[],hard:[],notes:{},learnedAt:{},nextReview:{},reviewLevel:{},studyDates:[]},JSON.parse(localStorage.getItem(KEY)||'{}'));
['learned','review','hard','studyDates'].forEach(k=>state[k]=Array.isArray(state[k])?state[k]:[]);
let cards=[],order=[],cardIndex=0,flipped=false,filter='all',noteArticle=null,reviewQueue=[],reviewIndex=0,reviewFlipped=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],has=(k,n)=>state[k].includes(n);
function save(action=true){if(action&&!state.studyDates.includes(todayKey()))state.studyDates.push(todayKey());localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(OLD_KEY,JSON.stringify([...state.learned].sort((a,b)=>a-b)));renderAll()}
function toggle(k,n,value=!has(k,n)){state[k]=state[k].filter(x=>x!==n);if(value)state[k].push(n)}
function learn(n,value=!has('learned',n)){toggle('learned',n,value);if(value){state.learnedAt[n]=Date.now();state.nextReview[n]=Date.now()+DAY}else{delete state.learnedAt[n];delete state.nextReview[n]}save()}
function markReview(n,value=!has('review',n)){toggle('review',n,value);if(value)state.nextReview[n]=Date.now();save()}
function markHard(n,value=!has('hard',n)){toggle('hard',n,value);save()}
function studyDaysLeft(){const start=new Date(DEADLINE);start.setDate(start.getDate()-REVIEW_DAYS);return Math.max(0,Math.ceil((start-new Date())/DAY))}
function dailyGoal(){const left=ARTICLES.length-state.learned.length,days=studyDaysLeft();return left===0?0:days?Math.ceil(left/days):left}
function formatDate(d){return new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'long'}).format(d)}
function streak(){const dates=new Set(state.studyDates),d=new Date();let total=0;if(!dates.has(todayKey()))d.setDate(d.getDate()-1);while(true){const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(!dates.has(k))break;total++;d.setDate(d.getDate()-1)}return total}
function forecast(){const left=ARTICLES.length-state.learned.length;if(!left)return 'Готово ✓';const d=new Date();d.setDate(d.getDate()+Math.ceil(left/Math.max(1,dailyGoal())));return formatDate(d)}
function renderMetrics(){const done=state.learned.length;$('#doneCount').textContent=done;$('#progressBar').style.width=`${done/ARTICLES.length*100}%`;$('#streak').textContent=streak();$('#forecast').textContent=forecast();const goal=dailyGoal(),left=ARTICLES.filter(n=>!has('learned',n));$('#todayTitle').textContent=goal===0?'План виконано':`${goal} ${goal===1?'стаття':goal<5?'статті':'статей'}`;$('#todayList').innerHTML=goal?left.slice(0,goal).map(n=>`<span>Стаття ${n}</span>`).join(''):'<span>Час повторювати ✓</span>';$('#dailyGoal').textContent=goal;const days=studyDaysLeft(),elapsed=Math.max(0,24-days),expected=Math.floor(elapsed*ARTICLES.length/24),lag=expected-done;let level=done===ARTICLES.length?'green':lag<=1?'green':lag<=4?'yellow':'red';if(!days&&done<ARTICLES.length)level='red';$('#pace').className=`pace ${level}`;$('#paceStatus').textContent=done===ARTICLES.length?'Усе вивчено':level==='green'?'Темп нормальний':level==='yellow'?'Час прискоритись':'Ризик не встигнути'}
function articleCard(n){const l=has('learned',n),r=has('review',n),h=has('hard',n),note=state.notes[n];return `<article class="article ${l?'learned':''} ${r?'review':''} ${h?'hard':''}" data-n="${n}"><div class="article-title">Стаття ${n}<small>Artikel ${n}</small></div><div class="article-state">${l?'Вивчено':''}${r?' · Повторити':''}${h?' · Складна':''}</div><div class="article-actions"><button class="learn-toggle ${l?'state-on':''}">${l?'✓ Вивчено':'Позначити вивчено'}</button><button class="review-toggle ${r?'state-on':''}">↻ Повторити</button><button class="hard-toggle ${h?'state-on':''}">! Складна</button><button class="note-toggle ${note?'state-on':''}">${note?'✎ Є нотатка':'＋ Нотатка'}</button><button class="wide open-card">Відкрити картку →</button></div></article>`}
function renderArticles(){const q=$('#search').value.trim();const shown=ARTICLES.filter(n=>(!q||String(n).includes(q))&&(filter==='all'||filter==='todo'&&!has('learned',n)||filter==='learned'&&has('learned',n)||filter==='review'&&has('review',n)||filter==='hard'&&has('hard',n)));$('#articleGrid').innerHTML=shown.map(articleCard).join('');$('#empty').style.display=shown.length?'none':'block'}
function dueArticles(){const now=Date.now();return ARTICLES.filter(n=>has('review',n)||(has('learned',n)&&state.nextReview[n]&&state.nextReview[n]<=now))}
function renderAll(){renderMetrics();renderArticles();$('#reviewBadge').textContent=dueArticles().length;renderCard()}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));if(name==='review')startReview(false);window.scrollTo({top:0,behavior:'smooth'})}
function mergeCards(raw){const grouped=new Map();raw.split(/\r?\n§§§\r?\n/).filter(Boolean).forEach(part=>{const split=part.indexOf('\t');if(split<0)return;const uk=part.slice(0,split).trim(),de=part.slice(split+1).trim(),m=uk.match(/Стаття\s+(\d+)/i);if(!m)return;const n=+m[1],cleanUk=uk.replace(/^Стаття\s+\d+\.\s*/i,''),cleanDe=de.replace(/^Artikel\s+\d+\.\s*/i,'');if(!grouped.has(n))grouped.set(n,{n,uk:`Стаття ${n}.`,de:`Artikel ${n}.`});const c=grouped.get(n);c.uk+=`\n${cleanUk}`;c.de+=`\n${cleanDe}`});return ARTICLES.map(n=>grouped.get(n)).filter(Boolean)}
async function loadCards(){try{cards=mergeCards(await fetch('cards.txt').then(r=>{if(!r.ok)throw Error();return r.text()}));order=cards.map((_,i)=>i);renderCard()}catch(e){$('#cardCopy').textContent='Не вдалося завантажити картки. Оновіть сторінку.'}}
function currentCard(){return cards[order[cardIndex]]}
function renderCard(){if(!cards.length)return;cardIndex=Math.max(0,Math.min(cardIndex,order.length-1));const c=currentCard();$('#cardSide').textContent=flipped?'Deutsch':'Українська';$('#cardCopy').textContent=flipped?c.de:c.uk;$('#cardCounter').textContent=`${cardIndex+1} / ${order.length}`;$('#cardLearned').textContent=has('learned',c.n)?'Вивчено ✓':'Знаю ✓';$('#cardReview').classList.toggle('state-on',has('review',c.n));$('#cardHard').classList.toggle('state-on',has('hard',c.n))}
function moveCard(step){cardIndex=(cardIndex+step+order.length)%order.length;flipped=false;renderCard()}
function openArticle(n){order=cards.map((_,i)=>i);cardIndex=Math.max(0,cards.findIndex(c=>c.n===n));flipped=false;switchView('cards');renderCard()}
function startReview(all){reviewQueue=(all?ARTICLES.filter(n=>has('learned',n)):dueArticles()).filter(n=>cards.some(c=>c.n===n));reviewIndex=0;reviewFlipped=false;$('#reviewEmpty').hidden=reviewQueue.length>0;$('#reviewSession').hidden=!reviewQueue.length;if(reviewQueue.length)renderReviewCard()}
function renderReviewCard(){const n=reviewQueue[reviewIndex],c=cards.find(x=>x.n===n);$('#reviewSide').textContent=reviewFlipped?'Deutsch':'Українська';$('#reviewCopy').textContent=reviewFlipped?c.de:c.uk;$('#reviewCounter').textContent=`${reviewIndex+1} / ${reviewQueue.length} · Стаття ${n}`}
function finishReview(known){const n=reviewQueue[reviewIndex];if(known){toggle('review',n,false);const level=(state.reviewLevel[n]||0)+1;state.reviewLevel[n]=level;state.nextReview[n]=Date.now()+[1,3,7,14][Math.min(level,3)]*DAY}else{toggle('review',n,true);state.nextReview[n]=Date.now()}save();reviewIndex++;reviewFlipped=false;if(reviewIndex>=reviewQueue.length)startReview(false);else renderReviewCard()}
function tick(){const left=Math.max(0,DEADLINE-new Date()),vals=[Math.floor(left/DAY),Math.floor(left/3600000)%24,Math.floor(left/60000)%60,Math.floor(left/1000)%60];['days','hours','minutes','seconds'].forEach((id,i)=>$(`#${id}`).textContent=String(vals[i]).padStart(2,'0'))}
$$('.tab').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('.filter').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderArticles()}));$('#search').addEventListener('input',renderArticles);
$('#articleGrid').addEventListener('click',e=>{const a=e.target.closest('.article');if(!a)return;const n=+a.dataset.n;if(e.target.closest('.learn-toggle'))learn(n);else if(e.target.closest('.review-toggle'))markReview(n);else if(e.target.closest('.hard-toggle'))markHard(n);else if(e.target.closest('.note-toggle')){noteArticle=n;$('#noteTitle').textContent=`Стаття ${n}`;$('#noteText').value=state.notes[n]||'';$('#noteDialog').showModal()}else if(e.target.closest('.open-card'))openArticle(n)});
$('#noteDialog').addEventListener('close',()=>{if($('#noteDialog').returnValue==='save'){const value=$('#noteText').value.trim();if(value)state.notes[noteArticle]=value;else delete state.notes[noteArticle];save()}});$('#flashcard').addEventListener('click',()=>{flipped=!flipped;renderCard()});$('#prevCard').addEventListener('click',()=>moveCard(-1));$('#nextCard').addEventListener('click',()=>moveCard(1));$('#shuffleBtn').addEventListener('click',()=>{order.sort(()=>Math.random()-.5);cardIndex=0;flipped=false;renderCard()});$('#cardLearned').addEventListener('click',()=>learn(currentCard().n,true));$('#cardReview').addEventListener('click',()=>markReview(currentCard().n));$('#cardHard').addEventListener('click',()=>markHard(currentCard().n));$('#startToday').addEventListener('click',()=>{const todo=ARTICLES.filter(n=>!has('learned',n)).slice(0,Math.max(1,dailyGoal()));order=todo.map(n=>cards.findIndex(c=>c.n===n)).filter(i=>i>=0);if(!order.length)order=cards.map((_,i)=>i);cardIndex=0;flipped=false;switchView('cards');renderCard()});
$('#reviewCard').addEventListener('click',()=>{reviewFlipped=!reviewFlipped;renderReviewCard()});$('#reviewAgain').addEventListener('click',()=>finishReview(false));$('#reviewKnown').addEventListener('click',()=>finishReview(true));$('#reviewAll').addEventListener('click',()=>startReview(true));$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`un-charta-progress-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)});$('#resetBtn').addEventListener('click',()=>{if(confirm('Скинути весь прогрес, статуси й нотатки?')){state={learned:[],review:[],hard:[],notes:{},learnedAt:{},nextReview:{},reviewLevel:{},studyDates:[]};save(false)}});
document.addEventListener('keydown',e=>{if(!$('#cardsView').classList.contains('active')||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowLeft')moveCard(-1);if(e.key==='ArrowRight')moveCard(1);if(e.code==='Space'){e.preventDefault();flipped=!flipped;renderCard()}});renderAll();tick();setInterval(tick,1000);loadCards();
