const ARTICLES=[1,2,3,4,5,6,7,8,9,10,11,17,18,20,22,23,24,27,28,32,33,34,41,42,43,45,50,51,55,61,62,75,92,97,98,102,103,110,111];
const OLD_KEY='un-charta-progress-v1',KEY='un-charta-study-v2',DEADLINE=new Date('2026-10-12T00:00:00+03:00'),DAY=86400000,REVIEW_DAYS=4;
const SUPABASE_URL='https://xwdxfbgazlplyiglzecm.supabase.co',SUPABASE_KEY='sb_publishable_yNV81pVLwznAKRN2fH3PBQ_ptbNVmFh';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const blankState=()=>({learned:[],review:[],hard:[],difficulty:{},notes:{},learnedAt:{},nextReview:{},reviewLevel:{},studyDates:[]});
function normalize(raw={}){const s=Object.assign(blankState(),raw);['learned','review','hard','studyDates'].forEach(k=>s[k]=Array.isArray(s[k])?s[k]:[]);s.difficulty=s.difficulty&&typeof s.difficulty==='object'?s.difficulty:{};s.hard.forEach(n=>{if(!s.difficulty[n])s.difficulty[n]='hard'});return s}
const oldLearned=JSON.parse(localStorage.getItem(OLD_KEY)||'[]');let state=normalize(Object.assign({learned:oldLearned},JSON.parse(localStorage.getItem(KEY)||'{}')));
let cards=[],order=[],cardIndex=0,flipped=false,filter='all',noteArticle=null,reviewQueue=[],reviewIndex=0,reviewFlipped=false,currentUser=null,cloudTimer=null,authMode='signin';
const has=(k,n)=>state[k].includes(n),todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const client=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
function save(action=true){if(action&&!state.studyDates.includes(todayKey()))state.studyDates.push(todayKey());localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(OLD_KEY,JSON.stringify([...state.learned].sort((a,b)=>a-b)));renderAll();queueCloudSave()}
function queueCloudSave(){if(!currentUser||!client)return;$('#syncText').textContent='Зберігаю в хмарі…';clearTimeout(cloudTimer);cloudTimer=setTimeout(saveCloud,450)}
async function saveCloud(){if(!currentUser)return;const {error}=await client.from('study_progress').upsert({user_id:currentUser.id,state,updated_at:new Date().toISOString()},{onConflict:'user_id'});$('#syncText').textContent=error?'Не вдалося синхронізувати. Зміни лишились у браузері.':'Збережено в хмарі ✓'}
async function useSession(session){currentUser=session?.user||null;renderAuthStatus();if(!currentUser)return;$('#syncText').textContent='Завантажую хмарний прогрес…';const {data,error}=await client.from('study_progress').select('state').eq('user_id',currentUser.id).maybeSingle();if(error){$('#syncText').textContent='Помилка завантаження. Локальний прогрес збережено.';return}if(data?.state){state=normalize(data.state);localStorage.setItem(KEY,JSON.stringify(state));renderAll();$('#syncText').textContent='Прогрес синхронізовано ✓'}else await saveCloud()}
function renderAuthStatus(){if(currentUser){$('#authBtn').textContent=currentUser.email;$('#syncText').textContent='Хмарне збереження увімкнено';$('#syncAction').textContent='Акаунт';$('#signOutBtn').hidden=false;$('#authSubmit').hidden=true;$('#authMode').hidden=true;$('#authEmail').value=currentUser.email;$('#authEmail').disabled=true;$('#authPassword').closest('label').hidden=true;$('#authTitle').textContent='Ваш акаунт'}else{$('#authBtn').textContent='Увійти';$('#syncText').textContent='Прогрес зберігається в цьому браузері';$('#syncAction').textContent='Увійти для хмарного збереження';$('#signOutBtn').hidden=true;$('#authSubmit').hidden=false;$('#authMode').hidden=false;$('#authEmail').disabled=false;$('#authPassword').closest('label').hidden=false;setAuthMode('signin')}}
function setAuthMode(mode){authMode=mode;$('#authTitle').textContent=mode==='signin'?'Увійти':'Створити акаунт';$('#authSubmit').textContent=mode==='signin'?'Увійти':'Зареєструватися';$('#authMode').textContent=mode==='signin'?'Немає акаунта? Зареєструватися':'Уже є акаунт? Увійти';$('#authPassword').autocomplete=mode==='signin'?'current-password':'new-password';$('#authMessage').textContent=''}
function toggle(k,n,value=!has(k,n)){state[k]=state[k].filter(x=>x!==n);if(value)state[k].push(n)}function learn(n,value=!has('learned',n)){toggle('learned',n,value);if(value){state.learnedAt[n]=Date.now();state.nextReview[n]=Date.now()+DAY}else{delete state.learnedAt[n];delete state.nextReview[n]}save()}function markReview(n,value=!has('review',n)){toggle('review',n,value);if(value)state.nextReview[n]=Date.now();save()}function setDifficulty(n,level){state.difficulty[n]=state.difficulty[n]===level?'':level;save()}
function studyDaysLeft(){const start=new Date(DEADLINE);start.setDate(start.getDate()-REVIEW_DAYS);return Math.max(0,Math.ceil((start-new Date())/DAY))}function dailyGoal(){const left=ARTICLES.length-state.learned.length,days=studyDaysLeft();return left===0?0:days?Math.ceil(left/days):left}function formatDate(d){return new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'long'}).format(d)}
function streak(){const dates=new Set(state.studyDates),d=new Date();let total=0;if(!dates.has(todayKey()))d.setDate(d.getDate()-1);while(true){const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(!dates.has(k))break;total++;d.setDate(d.getDate()-1)}return total}function forecast(){const left=ARTICLES.length-state.learned.length;if(!left)return'Готово ✓';const d=new Date();d.setDate(d.getDate()+Math.ceil(left/Math.max(1,dailyGoal())));return formatDate(d)}
function renderMetrics(){const done=state.learned.length;$('#doneCount').textContent=done;$('#progressBar').style.width=`${done/ARTICLES.length*100}%`;$('#streak').textContent=streak();$('#forecast').textContent=forecast();const goal=dailyGoal(),left=ARTICLES.filter(n=>!has('learned',n));$('#todayTitle').textContent=goal===0?'План виконано':`${goal} ${goal===1?'стаття':goal<5?'статті':'статей'}`;$('#todayList').innerHTML=goal?left.slice(0,goal).map(n=>`<span>Стаття ${n}</span>`).join(''):'<span>Час повторювати ✓</span>';$('#dailyGoal').textContent=goal;const days=studyDaysLeft(),lag=Math.floor(Math.max(0,24-days)*ARTICLES.length/24)-done;let level=done===ARTICLES.length?'green':lag<=1?'green':lag<=4?'yellow':'red';if(!days&&done<ARTICLES.length)level='red';$('#pace').className=`pace ${level}`;$('#paceStatus').textContent=done===ARTICLES.length?'Усе вивчено':level==='green'?'Темп нормальний':level==='yellow'?'Час прискоритись':'Ризик не встигнути'}
const levelName={easy:'Легка',medium:'Середня',hard:'Складна'};
function articleCard(n){const l=has('learned',n),r=has('review',n),d=state.difficulty[n]||'',note=state.notes[n];return `<article class="article ${l?'learned':''} ${r?'review':''} ${d}" data-n="${n}"><div class="article-title">Стаття ${n}<small>Artikel ${n}</small></div><div class="article-state">${l?'Вивчено':''}${r?' · Повторити':''}${d?' · '+levelName[d]:''}</div><div class="mini-difficulty"><button data-level="easy" class="${d==='easy'?'state-on':''}">Легка</button><button data-level="medium" class="${d==='medium'?'state-on':''}">Середня</button><button data-level="hard" class="${d==='hard'?'state-on':''}">Складна</button></div><div class="article-actions"><button class="learn-toggle ${l?'state-on':''}">${l?'✓ Вивчено':'Позначити вивчено'}</button><button class="review-toggle ${r?'state-on':''}">↻ Повторити</button><button class="note-toggle ${note?'state-on':''}">${note?'✎ Є нотатка':'＋ Нотатка'}</button><button class="open-card">Відкрити картку →</button></div></article>`}
function renderArticles(){const q=$('#search').value.trim();const shown=ARTICLES.filter(n=>(!q||String(n).includes(q))&&(filter==='all'||filter==='todo'&&!has('learned',n)||filter==='learned'&&has('learned',n)||filter==='review'&&has('review',n)||['easy','medium','hard'].includes(filter)&&state.difficulty[n]===filter));$('#articleGrid').innerHTML=shown.map(articleCard).join('');$('#empty').style.display=shown.length?'none':'block'}function dueArticles(){const now=Date.now();return ARTICLES.filter(n=>has('review',n)||(has('learned',n)&&state.nextReview[n]&&state.nextReview[n]<=now))}function renderAll(){renderMetrics();renderArticles();$('#reviewBadge').textContent=dueArticles().length;renderCard()}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));if(name==='review')startReview(false);window.scrollTo({top:0,behavior:'smooth'})}
function mergeCards(raw){const grouped=new Map();raw.split(/\r?\n§§§\r?\n/).filter(Boolean).forEach(part=>{const split=part.indexOf('\t');if(split<0)return;const uk=part.slice(0,split).trim(),de=part.slice(split+1).trim(),m=uk.match(/Стаття\s+(\d+)/i);if(!m)return;const n=+m[1],u=uk.replace(/^Стаття\s+\d+\.\s*/i,''),g=de.replace(/^Artikel\s+\d+\.\s*/i,'');if(!grouped.has(n))grouped.set(n,{n,uk:`Стаття ${n}.`,de:`Artikel ${n}.`});grouped.get(n).uk+=`\n${u}`;grouped.get(n).de+=`\n${g}`});return ARTICLES.map(n=>grouped.get(n)).filter(Boolean)}
async function loadCards(){try{cards=mergeCards(await fetch('cards.txt').then(r=>{if(!r.ok)throw Error();return r.text()}));order=cards.map((_,i)=>i);renderCard()}catch(e){$('#cardUk').textContent='Не вдалося завантажити картки. Оновіть сторінку.'}}function currentCard(){return cards[order[cardIndex]]}
function renderCard(){if(!cards.length)return;cardIndex=Math.max(0,Math.min(cardIndex,order.length-1));const c=currentCard();$('#cardUk').textContent=c.uk;$('#cardDe').textContent=c.de;$('#flashcard').classList.toggle('flipped',flipped);$('#cardCounter').textContent=`${cardIndex+1} / ${order.length}`;$('#cardLearned').textContent=has('learned',c.n)?'Вивчено ✓':'Знаю ✓';$('#cardReview').classList.toggle('state-on',has('review',c.n));$$('.difficulty-actions button').forEach(b=>b.classList.toggle('state-on',state.difficulty[c.n]===b.dataset.level))}
function animateCard(step){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;$('#flashcard').animate([{opacity:.35,transform:`translateX(${step>0?'18px':'-18px'})`},{opacity:1,transform:'translateX(0)'}],{duration:180,easing:'cubic-bezier(0.23, 1, 0.32, 1)'})}function moveCard(step){cardIndex=(cardIndex+step+order.length)%order.length;flipped=false;renderCard();animateCard(step)}function openArticle(n){order=cards.map((_,i)=>i);cardIndex=Math.max(0,cards.findIndex(c=>c.n===n));flipped=false;switchView('cards');renderCard()}
function startReview(all){reviewQueue=(all?ARTICLES.filter(n=>has('learned',n)):dueArticles()).filter(n=>cards.some(c=>c.n===n));reviewIndex=0;reviewFlipped=false;$('#reviewEmpty').hidden=reviewQueue.length>0;$('#reviewSession').hidden=!reviewQueue.length;if(reviewQueue.length)renderReviewCard()}function renderReviewCard(){const n=reviewQueue[reviewIndex],c=cards.find(x=>x.n===n);$('#reviewUk').textContent=c.uk;$('#reviewDe').textContent=c.de;$('#reviewCard').classList.toggle('flipped',reviewFlipped);$('#reviewCounter').textContent=`${reviewIndex+1} / ${reviewQueue.length} · Стаття ${n}`}function finishReview(known){const n=reviewQueue[reviewIndex];if(known){toggle('review',n,false);const level=(state.reviewLevel[n]||0)+1;state.reviewLevel[n]=level;state.nextReview[n]=Date.now()+[1,3,7,14][Math.min(level,3)]*DAY}else{toggle('review',n,true);state.nextReview[n]=Date.now()}save();reviewIndex++;reviewFlipped=false;if(reviewIndex>=reviewQueue.length)startReview(false);else renderReviewCard()}
function tick(){const left=Math.max(0,DEADLINE-new Date()),vals=[Math.floor(left/DAY),Math.floor(left/3600000)%24,Math.floor(left/60000)%60,Math.floor(left/1000)%60];['days','hours','minutes','seconds'].forEach((id,i)=>$(`#${id}`).textContent=String(vals[i]).padStart(2,'0'))}
$$('.tab').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('.filter').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderArticles()}));$('#search').addEventListener('input',renderArticles);$('#articleGrid').addEventListener('click',e=>{const a=e.target.closest('.article');if(!a)return;const n=+a.dataset.n;if(e.target.closest('[data-level]'))setDifficulty(n,e.target.closest('[data-level]').dataset.level);else if(e.target.closest('.learn-toggle'))learn(n);else if(e.target.closest('.review-toggle'))markReview(n);else if(e.target.closest('.note-toggle')){noteArticle=n;$('#noteTitle').textContent=`Стаття ${n}`;$('#noteText').value=state.notes[n]||'';$('#noteDialog').showModal()}else if(e.target.closest('.open-card'))openArticle(n)});
$('#noteDialog').addEventListener('close',()=>{if($('#noteDialog').returnValue==='save'){const v=$('#noteText').value.trim();if(v)state.notes[noteArticle]=v;else delete state.notes[noteArticle];save()}});$('#flashcard').addEventListener('click',()=>{flipped=!flipped;renderCard()});$('#prevCard').addEventListener('click',()=>moveCard(-1));$('#nextCard').addEventListener('click',()=>moveCard(1));$('#shuffleBtn').addEventListener('click',()=>{order.sort(()=>Math.random()-.5);cardIndex=0;flipped=false;renderCard()});$('#cardLearned').addEventListener('click',()=>learn(currentCard().n,true));$('#cardReview').addEventListener('click',()=>markReview(currentCard().n));$$('.difficulty-actions button').forEach(b=>b.addEventListener('click',()=>setDifficulty(currentCard().n,b.dataset.level)));$('#startToday').addEventListener('click',()=>{const todo=ARTICLES.filter(n=>!has('learned',n)).slice(0,Math.max(1,dailyGoal()));order=todo.map(n=>cards.findIndex(c=>c.n===n)).filter(i=>i>=0);if(!order.length)order=cards.map((_,i)=>i);cardIndex=0;flipped=false;switchView('cards');renderCard()});
$('#reviewCard').addEventListener('click',()=>{reviewFlipped=!reviewFlipped;renderReviewCard()});$('#reviewAgain').addEventListener('click',()=>finishReview(false));$('#reviewKnown').addEventListener('click',()=>finishReview(true));$('#reviewAll').addEventListener('click',()=>startReview(true));$('#resetBtn').addEventListener('click',()=>{if(confirm('Скинути весь прогрес, статуси й нотатки?')){state=blankState();save(false)}});
function openAuth(){renderAuthStatus();$('#authMessage').textContent='';$('#authDialog').showModal()}$('#authBtn').addEventListener('click',openAuth);$('#syncAction').addEventListener('click',openAuth);$('#closeAuth').addEventListener('click',()=>$('#authDialog').close());$('#authMode').addEventListener('click',()=>setAuthMode(authMode==='signin'?'signup':'signin'));$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value;$('#authSubmit').disabled=true;$('#authMessage').textContent='Зачекайте…';const result=authMode==='signin'?await client.auth.signInWithPassword({email,password}):await client.auth.signUp({email,password,options:{emailRedirectTo:'https://vitthegrandfather.github.io/un-charter-checklist/'}});$('#authSubmit').disabled=false;if(result.error){$('#authMessage').textContent=result.error.message;return}if(authMode==='signup'&&!result.data.session){$('#authMessage').textContent='Перевірте пошту та підтвердьте реєстрацію.'}else{$('#authDialog').close();await useSession(result.data.session)}});$('#signOutBtn').addEventListener('click',async()=>{await client.auth.signOut();currentUser=null;state=blankState();localStorage.removeItem(KEY);localStorage.removeItem(OLD_KEY);$('#authDialog').close();renderAuthStatus();renderAll()});
document.addEventListener('keydown',e=>{if(!$('#cardsView').classList.contains('active')||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowLeft')moveCard(-1);if(e.key==='ArrowRight')moveCard(1);if(e.code==='Space'){e.preventDefault();flipped=!flipped;renderCard()}});
renderAll();renderAuthStatus();tick();setInterval(tick,1000);loadCards();if(client){client.auth.getSession().then(({data})=>useSession(data.session));client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session?.user?.id!==currentUser?.id)setTimeout(()=>useSession(session),0);if(event==='SIGNED_OUT'){currentUser=null;renderAuthStatus()}})}
